from PySide6.QtCore import QCoreApplication, QMetaObject, QRect, QSize, Qt
from PySide6.QtGui import QFont
from PySide6.QtWidgets import QFrame, QHBoxLayout, QLabel, QLayout, QPushButton, QSizePolicy, QStackedWidget, QVBoxLayout, QWidget

class SeriesOptions(object):
    
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"SeriesOptions")
        MainWindow.resize(599, 529)
        MainWindow.setStyleSheet(u"background-color: rgb(192, 191, 188);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.sidebar = QFrame(self.centralwidget)
        self.sidebar.setObjectName(u"sidebar")
        self.sidebar.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy1)
        self.sidebar.setMinimumSize(QSize(150, 500))
        font = QFont()
        font.setKerning(True)
        self.sidebar.setFont(font)
        self.sidebar.setAutoFillBackground(False)
        self.sidebar.setStyleSheet(u"background-color: rgb(119, 118, 123);")
        self.sidebar.setFrameShape(QFrame.NoFrame)
        self.sidebar.setFrameShadow(QFrame.Sunken)
        self.sidebar.setLineWidth(1)
        self.verticalLayout = QVBoxLayout(self.sidebar)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.btn_container = QFrame(self.sidebar)
        self.btn_container.setObjectName(u"btn_container")
        self.btn_container.setFrameShape(QFrame.NoFrame)
        self.btn_container.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.btn_container)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.btn_series = QPushButton(self.btn_container)
        self.btn_series.setObjectName(u"btn_series")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.btn_series.sizePolicy().hasHeightForWidth())
        self.btn_series.setSizePolicy(sizePolicy2)
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setKerning(True)
        self.btn_series.setFont(font1)
        self.btn_series.setAcceptDrops(False)
        self.btn_series.setAutoFillBackground(False)
        self.btn_series.setStyleSheet(u"background-color: rgb(192, 191, 188);")
        self.btn_series.setCheckable(False)
        self.btn_series.setFlat(False)

        self.verticalLayout_2.addWidget(self.btn_series)

        self.btn_rendering = QPushButton(self.btn_container)
        self.btn_rendering.setObjectName(u"btn_rendering")
        self.btn_rendering.setAutoFillBackground(False)
        self.btn_rendering.setStyleSheet(u"background-color: rgb(192, 191, 188);")
        self.btn_rendering.setFlat(False)

        self.verticalLayout_2.addWidget(self.btn_rendering)

        self.btn_interface = QPushButton(self.btn_container)
        self.btn_interface.setObjectName(u"btn_interface")
        self.btn_interface.setAutoFillBackground(False)
        self.btn_interface.setStyleSheet(u"background-color: rgb(192, 191, 188);")
        self.btn_interface.setFlat(False)

        self.verticalLayout_2.addWidget(self.btn_interface)

        self.btn_navigation = QPushButton(self.btn_container)
        self.btn_navigation.setObjectName(u"btn_navigation")
        sizePolicy3 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.btn_navigation.sizePolicy().hasHeightForWidth())
        self.btn_navigation.setSizePolicy(sizePolicy3)
        self.btn_navigation.setFocusPolicy(Qt.WheelFocus)
        self.btn_navigation.setAutoFillBackground(False)
        self.btn_navigation.setStyleSheet(u"background-color: rgb(192, 191, 188);")
        self.btn_navigation.setFlat(False)

        self.verticalLayout_2.addWidget(self.btn_navigation)


        self.verticalLayout.addWidget(self.btn_container, 0, Qt.AlignTop)


        self.horizontalLayout.addWidget(self.sidebar)

        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet(u"")
        self.Series = QWidget()
        self.Series.setObjectName(u"Series")
        self.series_label = QLabel(self.Series)
        self.series_label.setObjectName(u"series_label")
        self.series_label.setGeometry(QRect(120, 160, 161, 71))
        self.stackedWidget.addWidget(self.Series)
        self.Rendering = QWidget()
        self.Rendering.setObjectName(u"Rendering")
        self.rendering_label = QLabel(self.Rendering)
        self.rendering_label.setObjectName(u"rendering_label")
        self.rendering_label.setGeometry(QRect(110, 250, 171, 16))
        self.stackedWidget.addWidget(self.Rendering)
        self.Interface = QWidget()
        self.Interface.setObjectName(u"Interface")
        self.interface_label = QLabel(self.Interface)
        self.interface_label.setObjectName(u"interface_label")
        self.interface_label.setGeometry(QRect(160, 180, 161, 111))
        self.stackedWidget.addWidget(self.Interface)
        self.Navigation = QWidget()
        self.Navigation.setObjectName(u"Navigation")
        self.navigation_label = QLabel(self.Navigation)
        self.navigation_label.setObjectName(u"navigation_label")
        self.navigation_label.setGeometry(QRect(110, 170, 201, 111))
        self.stackedWidget.addWidget(self.Navigation)

        self.horizontalLayout.addWidget(self.stackedWidget)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.btn_series.setDefault(False)
        self.stackedWidget.setCurrentIndex(1)

        QMetaObject.connectSlotsByName(MainWindow)

        
    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Options", None))
        self.btn_series.setText(QCoreApplication.translate("MainWindow", u"Series", None))
        self.btn_rendering.setText(QCoreApplication.translate("MainWindow", u"Rendering", None))
        self.btn_interface.setText(QCoreApplication.translate("MainWindow", u"Interface", None))
        self.btn_navigation.setText(QCoreApplication.translate("MainWindow", u"Navigation", None))
        self.series_label.setText(QCoreApplication.translate("MainWindow", u"Series options to go here", None))
        self.rendering_label.setText(QCoreApplication.translate("MainWindow", u"Rendering", None))
        self.interface_label.setText(QCoreApplication.translate("MainWindow", u"Interface options", None))
        self.navigation_label.setText(QCoreApplication.translate("MainWindow", u"Navigation label here!", None))
