* Windows machines

Dealing with dependencies can be a hassle. To make things simple for Windows users, we've written batch scripts that will take care of downloading and sourcing dependencies.

(If you're comfortable with creating virtual environments and downloading dependencies, you can ignore these two scripts. If you'd rather us take care of this, continue below.)

** Make sure you've got Python

Make sure you're running at least Python version 3.9. You can check this in Windows by opening command prompt and running =python --version=. Newer versions of Python can be downloaded in the Microsoft App Store.

** Clone the repository

Clone the pyReconstruct repository wherever you would like on your machine using GitHub Desktop or good ol' git (=git clone https://github.com/SynapseWeb/pyReconstruct=).

** Install dependencies via install.bat

=install.bat= will install dependencies listed in =src/requirements.txt= in a virtual environment that will be stored in a newly created =env= directory. As long as dependencies do not change, you should only have to run this script once before launching pyReconstruct the first time.

** Launch pyReconstruct via pyReconstruct.bat

=pyReconstruct.bat= will launch pyReconstruct and source dependencies from =env=. You should use this script to start pyReconstruct if you've installed the dependencies using =install.bat=.

=pyReconstruct.bat= does three things:

 1. activates (starts) the virtual environment.
 2. Runs =src/pyReconstruct.py=.
 3. Deactivates the virtual environment when the program is closed.

From this point forward, you should use =pyReconstruct.bat= to launch the program.
