#+TITLE: Welcome to the GitHub repository for pyReconstruct!
#+OPTIONS: toc:nil

* PyReconstruct

pyReconstruct is an updated, actively maintained, and extensible version of RECONSTRUCT written entirely in Python using Python versions 3.9 and 3.10.

Though this his project is still in its infancy stages, but we are happy to share with you what we have so far.

* Repository structure

This GitHub repository is structured to be easily understandable. All source files can be found under ~src/~ and other file types are here:

|------------------------------------+----------------------|
| File type(s)                       | Location             |
|------------------------------------+----------------------|
| Script to run pyReconstruct        | src/pyReconstruct.py |
| List of dependencies               | src/requirements.txt |
| Modules                            | src/modules          |
| Images and example series          | src/assets           |
| File locations and other constants | src/constants        |
| Notes and features                 | notes/               |
| Miscellaneous                      | misc/                |
|------------------------------------+----------------------|

* Dependencies

Dependencies needed to run pyReconstruct can be found in this repo (~/src/requirements.txt~) and can be installed via PIP: =pip install -r requirements.txt=

Using virtual environments such as Python's built-in /venv/ module is an excellent way of managing dependencies necessary to run pyReconstruct.

Here is an example of installing dependencies in a newly created virtual environment in Linux:

- Change current working directory to your local copy of this repo: =cd /path/to/local/repo=
- Create a virtual environment (for this example, we will call it "env"): =python -m venv env=
- Activate the virtual environment: =source env/bin/activate=
- Install dependencies: =pip install -r src/requirements.txt=

* Running pyReconstruct

Once in the correct directory, pyReconstruct can be started with the following command:

=python pyReconstruct.py=


