from .trace import TraceDialog
from .object_group import ObjectGroupDialog
from .alignment import AlignmentDialog
from .grid import GridDialog
from .create_zarr import CreateZarrDialog
from .addto_zarr import AddToZarrDialog
from .train import TrainDialog
from .segment import SegmentDialog
from .predict import PredictDialog
from .shapes import ShapesDialog
from .trace_palette import TracePaletteDialog
from .quick_dialog import QuickDialog, QuickTabDialog
from .flag import FlagDialog
from .file_dialog import FileDialog
from .all_options import AllOptionsDialog
from .bc_profiles import BCProfilesDialog
from .backup import BackupDialog
from .shortcuts import ShortcutsDialog
from .backup_comment import BackupCommentDialog
from .table_columns import TableColumnsDialog
from .import_series import ImportSeriesDialog