#!/usr/bin/env python

import sys
import re
from pathlib import Path
from typing import Union


class GridFile:

    def __init__(self, filepath):

        self.filepath = Path(filepath)
        self.name = filepath.name
        self.grid_pattern = r'^(.*?)_(g|G|grid|Grid)(\d+).*?(s|S|section|Section)(\d+)_(.*?)$'
        self.name_corrected = self.correct_name()

    @property 
    def matches_pattern(self) -> bool:

        regexp = re.compile(self.grid_pattern)
        matches = True if regexp.search(self.name) else False

        return matches

    @property
    def name_parts(self) -> tuple:

        match = re.match(self.grid_pattern, self.name)
    
        before_g  = match.group(1)
        g_number  = match.group(3)
        s_number  = match.group(5)
        end       = match.group(6)

        return before_g, g_number, s_number, end

    def correct_name(self) -> Union[str, None]:
        """Get corrected name."""

        if self.matches_pattern:

            start, grid, section, end = self.name_parts

            return f"{start}_G{grid:0>3}_S{section:0>3}_{end}"
    
        else:

            return None

    def rename_file(self) -> None:

        if self.matches_pattern and self.name_corrected:

            new_path = self.filepath.with_name(self.name_corrected)
            self.filepath.rename(new_path)

            print(f"{self.name} → {self.name_corrected}")


class ImgDir:

    def __init__(self, directory):

        self.directory = Path(directory)

        if not self.directory.exists():
            
            raise FileNotFoundError(f"The directory {self.directory} does not exist.")
        
        if not self.directory.is_dir():
            
            raise NotADirectoryError(f"{self.directory} is not a directory.")

    def correct_grid_naming(self):

        for f in self.directory.iterdir():

            GridFile(f).rename_file()

def usage():

    print("Usage: fix-grid-numbering <directory>")
    sys.exit()


if __name__ == "__main__":

    if len(sys.argv) != 2:

        usage()

    my_dir = ImgDir(sys.argv[1])
    my_dir.correct_grid_naming()
    sys.exit(0)
