kh_web = "https://synapseweb.clm.utexas.edu/harrislab"
kh_wiki = "https://wikis.utexas.edu/display/khlab/PyReconstruct+user+guide"
kh_atlas = "https://synapseweb.clm.utexas.edu/atlas"
gh_repo = "https://github.com/SynapseWeb/PyReconstruct"
gh_issues = gh_repo + "/issues"
gh_submit = gh_issues + "/new/choose"
