name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-12]
        python-version: ['3.10']

    steps:
    
    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Qt on Linux
      if: runner.os == 'Linux'
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        install-deps: 'true'

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: sudo apt install libxcb1-dev

    - name: Install Qt on Windows
      if: runner.os == 'Windows'
      uses: jurplel/install-qt-action@v3
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
        	
    - name: Run tox test
      run: |
        tox
